[2023-06-15T17:02:45.056+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2023-06-15T17:01:40.456285+00:00 [queued]>
[2023-06-15T17:02:45.164+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2023-06-15T17:01:40.456285+00:00 [queued]>
[2023-06-15T17:02:45.173+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T17:02:45.175+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T17:02:45.176+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T17:02:45.299+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2023-06-15 17:01:40.456285+00:00
[2023-06-15T17:02:45.498+0000] {standard_task_runner.py:55} INFO - Started process 31774 to run task
[2023-06-15T17:02:45.921+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task', 'manual__2023-06-15T17:01:40.456285+00:00', '--job-id', '444', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp0qh2kxne']
[2023-06-15T17:02:45.998+0000] {standard_task_runner.py:83} INFO - Job 444: Subtask format_to_parquet_task
[2023-06-15T17:02:48.799+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2023-06-15T17:01:40.456285+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T17:02:49.467+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T17:01:40.456285+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T17:01:40.456285+00:00
[2023-06-15T17:02:49.486+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 26, in format_to_parquet
    for filename in os.listdir(src_file):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/direct-messaging'
[2023-06-15T17:02:49.550+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=format_to_parquet_task, execution_date=20230615T170140, start_date=20230615T170245, end_date=20230615T170249
[2023-06-15T17:02:49.651+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 444 for task format_to_parquet_task ([Errno 2] No such file or directory: '/opt/airflow/direct-messaging'; 31774)
[2023-06-15T17:02:49.804+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T17:02:50.173+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
